#!/usr/bin/env python3
"""Combine per-distractor filter_results_*.json into a single V3+V4 table.

Reads evaluation/m4c_geometry_filter/filter_results_*.json and prints a
markdown table summarising KEEP / REJECT counts per class for each set.

Optionally writes evaluation/m4c_geometry_filter/v3_v4_summary.md.

Usage:
  python3 scripts/m4c_v3v4_summary.py                # print to stdout
  python3 scripts/m4c_v3v4_summary.py --write-md    # also write the .md file
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
M4C = ROOT / "evaluation" / "m4c_geometry_filter"

# Order in which to display rows. Sets not present are simply skipped.
ORDER = [
    ("bottle",   "V3 bottle  (~60x60x150 mm cylinder)"),
    ("ball",     "V3 ball    (~80 mm sphere)"),
    ("cup",      "V3 cup     (~80x80x100 mm cylinder)"),
    ("carton",   "V3 carton  (~60x40x120 mm)"),
    ("tall_cyl", "V3 tall_cyl (~50x50x200 mm)"),
    ("cube_toy", "V3 cube_toy (~50 mm, non-rgb)"),
    ("empty",    "V4 empty   (no cubes)"),
    # V1/V2 baselines from M4c1 — kept for cross-reference
    ("cubes",    "V1+V2 cubes (M4c1 reference)"),
]


def load_filter(prefix: str) -> dict | None:
    p = M4C / f"filter_results_{prefix}.json"
    if not p.exists():
        return None
    return json.loads(p.read_text())


def per_class_line(d: dict) -> str:
    pc = d.get("per_class", {})
    parts = []
    for cls in ("blue_cube", "green_cube", "red_cube"):
        c = pc.get(cls, {})
        parts.append(f"{cls[:1]}={c.get('kept', 0)}/{c.get('input', 0)}")
    return " ".join(parts)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--write-md", action="store_true",
                   help="write evaluation/m4c_geometry_filter/v3_v4_summary.md")
    args = p.parse_args()

    rows: list[tuple[str, str, str, int, int, int, str]] = []
    for prefix, display in ORDER:
        d = load_filter(prefix)
        if d is None:
            rows.append((prefix, display, "MISSING", 0, 0, 0, ""))
            continue
        pc = d.get("per_class", {})
        rr = d.get("reject_reasons", {})
        rows.append((
            prefix,
            display,
            "ok",
            d.get("num_kept", 0),
            d.get("num_rejected", 0),
            d.get("num_input_detections", 0),
            per_class_line(d),
        ))

    md_lines = []
    md_lines.append("# M4c1 follow-up: V3 + V4 summary\n")
    md_lines.append("Generated by `scripts/m4c_v3v4_summary.py`.\n")
    md_lines.append("| Set | Display | Status | KEEP | REJECT | Input | per-class (kept/input) | reject reasons |")
    md_lines.append("|-----|---------|--------|-----:|-------:|------:|------------------------|----------------|")
    for prefix, display, status, k, rj, inp, pc_line in rows:
        d = load_filter(prefix)
        rr = d.get("reject_reasons", {}) if d else {}
        rr_str = ", ".join(f"{k}={v}" for k, v in rr.items() if v) if rr else "-"
        md_lines.append(
            f"| `{prefix}` | {display} | {status} | {k} | {rj} | {inp} | {pc_line} | {rr_str} |"
        )

    md_lines.append("")
    md_lines.append("**Pass criteria:**")
    md_lines.append("- V3 sets (bottle, ball, cup, carton, tall_cyl, cube_toy): **KEEP == 0** across all 30 frames at conf 0.25.")
    md_lines.append("- V4 empty set: **KEEP == 0** across all 30 frames at conf 0.25 AND at conf 0.50.")
    md_lines.append("- V1+V2 cubes reference (M4c1): V1 blue_cube kept >=22/30, V1 red_cube kept 0/30 (YOLO bbox issue, out of scope here), V2 all flat distractors rejected 30/30 each, V3 green bag rejected 64/64.")

    md = "\n".join(md_lines) + "\n"
    print(md)

    if args.write_md:
        out = M4C / "v3_v4_summary.md"
        out.write_text(md)
        print(f"wrote {out}", file=__import__("sys").stderr)

    # exit 0 if all required (V3 + V4) sets are present, else 1
    required = {"bottle", "ball", "cup", "carton", "tall_cyl", "cube_toy", "empty"}
    have = {r[0] for r in rows if r[2] == "ok"}
    missing = required - have
    return 0 if not missing else 1


if __name__ == "__main__":
    raise SystemExit(main())